spring:
  application:
    name: enterprise-policy-orchestrator-backend
  jackson:
    time-zone: Europe/Warsaw
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Warsaw
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN:dev-g5210pz7rpmrl82z.us.auth0.com}/
          jwk-set-uri: https://${AUTH0_DOMAIN:dev-g5210pz7rpmrl82z.us.auth0.com}/.well-known/jwks.json
